version: "3.8"
services:
  e2e:
    image: rag_e2e_test_pipeline
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - BASE_URL=${BASE_URL:-http://host.docker.internal:8000}
      - UPLOAD_STATUS_PATH=${UPLOAD_STATUS_PATH:-/documents/upload}
      - CI=true
    volumes:
      # Mount project
      - ..:/app

      # Persist Allure artifacts
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report

    network_mode: "host" # Linux only
    # On Mac/Windows, remove this and rely on host.docker.internal

    command: >
      sh -lc "npm run test:all && npm run allure:generate"